stages:
  data_ingestion:
    cmd: python src/pipeline.py
    deps:
      - src/pipeline.py
      - src/ingest_data.py
      - data/raw/sepsis_datasets.csv
    params:
      - data.input_file
      - data.raw_dir
    outs:
      - data/raw/ingested_*.csv
    metrics:
      - metrics/ingestion_metrics.json:
          cache: false

  data_preprocessing:
    cmd: python src/pipeline.py
    deps:
      - src/preprocess.py
      - data/raw/ingested_*.csv
    params:
      - preprocessing.numerical_features
      - preprocessing.categorical_features
      - preprocessing.text_features
      - preprocessing.target
      - preprocessing.text_vectorizer_params
      - data.processed_dir
    outs:
      - data/processed/processed_*.npz
      - data/processed/X_transformed.csv
      - data/processed/y_transformed.csv
      - data/processed/cleaned_data.csv
      - model/preprocessor.joblib
    metrics:
      - metrics/preprocessing_metrics.json:
          cache: false

  model_training:
    cmd: python src/pipeline.py
    deps:
      - src/train.py
      - data/processed/processed_*.npz
    params:
      - model.name
      - model.test_size
      - model.random_state
      - model.hyperparameters
      - data.model_dir
    outs:
      - model/trained_model.joblib
    metrics:
      - metrics/training_metrics.json:
          cache: false
      - metrics/validation_metrics.json:
          cache: false

  monitoring:
    cmd: python src/monitor.py
    deps:
      - src/monitor.py
      - model/trained_model.joblib
    params:
      - monitoring.enable_drift_detection
      - monitoring.drift_threshold
      - monitoring.features_to_monitor
    metrics:
      - metrics/drift_metrics.json:
          cache: false