# Dataset configurations
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  model_dir: "model"
  input_file: "data/raw/sepsis_datasets.csv"
  reference_data: "data/processed/reference_data.npz"  # Added reference data path

# Preprocessing settings
preprocessing:
  numerical_features:
    - "Age"
    - "Heart_Rate"
    - "BP_Systolic"
    - "BP_Diastolic"
    - "Temperature"
    - "Respiratory_Rate"
    - "WBC_Count"
    - "Lactate_Level"
  categorical_features:
    - "Gender"
    - "Comorbidities"
  text_features:
    - "Clinical_Notes"
  target: "Sepsis_Label"
  text_vectorizer_params:
    max_features: 100
    ngram_range: [1, 2]
    stop_words: "english"

# Model configurations
model:
  name: "RandomForest"
  test_size: 0.2
  random_state: 42
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    class_weight: "balanced"
  monitoring_metrics:  # Added model performance metrics to monitor
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"

# Monitoring configurations
monitoring:
  enable_drift_detection: true
  monitoring_dir: "monitoring"  # Directory for storing monitoring artifacts
  history_file: "monitoring/drift_history.json"  # File to store drift history
  visualizations_dir: "monitoring/visualizations"  # Directory for drift visualizations
  
  # Drift detection thresholds
  drift_thresholds:
    data_drift_threshold: 0.1  # KS test threshold for individual features
    concept_drift_threshold: 0.05  # Performance drop threshold
    label_drift_threshold: 0.1  # Label distribution change threshold
    evidently_drift_threshold: 0.2  # Share of drifted features threshold (for Evidently)
    significant_drift_ratio: 0.3  # Ratio of features that must drift to trigger alert
  
  # Features to monitor (expanded from original)
  features_to_monitor:
    numerical:
      - "Age"
      - "Heart_Rate"
      - "BP_Systolic"
      - "BP_Diastolic"
      - "Temperature"
      - "Respiratory_Rate"
      - "WBC_Count"
      - "Lactate_Level"
    categorical:
      - "Gender"
      - "Comorbidities"
  
  # Monitoring schedule
  schedule:
    daily: true
    weekly: false
    monthly: false
    time: "09:00"  # Time to run daily monitoring
  
  # Alerting configuration
  alerts:
    email_notifications: false
    email_recipients: []
    slack_notifications: false
    slack_webhook: ""
    minimum_severity: "high"  # Can be "low", "medium", "high"

retraining:
  enabled: true
  strategy: "performance_based"  # performance_based|scheduled|manual
  performance_threshold: 0.75  # F1 score threshold
  max_retrains: 3  # Max retrains before full retraining
  schedule:
    interval: "monthly"  # weekly|monthly|quarterly
    day: 1  # Day of month/week
    
  data:
    lookback_window: 90  # days
    min_samples: 1000
    
  validation:
    enabled: true
    threshold: 0.7  # Minimum validation score
    metrics:
      - "f1"
      - "roc_auc"

# MLflow tracking
mlflow:
  enabled: true
  tracking_uri: "sqlite:///mlruns.db"
  artifact_location: "mlruns"
  experiment_name: "sepsis_prediction"
  registered_model_name: "sepsis_risk_model"