# Dataset configurations
data:
  raw_path: "data/raw/dataset.csv"
  processed_path: "data/processed/processed_data.csv"

# Preprocessing settings
preprocessing:
  missing_values: "drop"  # Options: drop, fill_mean, fill_median
  encode_categorical: true
  scaling_method: "standard"  # Options: standard, minmax, robust

# Model configurations
model:
  name: "RandomForest"
  train_test_split: 0.8
  hyperparameters:
    n_estimators: 100
    max_depth: 10

# Monitoring configurations
monitoring:
  enable_drift_detection: true
  drift_threshold: 0.05
